services:
  php:
    image: tugboatqa/php:8.2-apache
    default: true
    depends: mysql
    commands:
      init:
        - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
        - a2enmod rewrite

      update:
        - composer install --no-dev
        - chown -R www-data:www-data /var/www/html
        
        # Simple Apache config
        - sed -i 's|DocumentRoot /var/www/html|DocumentRoot /var/www/html/web|' /etc/apache2/sites-available/000-default.conf
        - service apache2 reload
        
        # Basic Drupal settings
        - cp web/sites/default/default.settings.php web/sites/default/settings.php
        - |
          cat >> web/sites/default/settings.php << 'EOF'
          $databases['default']['default'] = [
            'database' => 'tugboat',
            'username' => 'tugboat', 
            'password' => 'tugboat',
            'host' => 'mysql',
            'port' => '3306',
            'driver' => 'mysql',
          ];
          $settings['trusted_host_patterns'] = ['^.+\.tugboat\.qa$'];
          EOF

      build:
        - ./vendor/bin/drush site:install --yes --account-name=admin --account-pass=admin
        - chown -R www-data:www-data web/sites/default/files

  mysql:
    image: tugboatqa/mysql:8.0
    commands:
      update:
        - mysql -e "CREATE DATABASE IF NOT EXISTS tugboat;"
