services:
  php:
    image: tugboatqa/php:8.2-apache
    default: true
    depends: mysql
    commands:
      init:
        # Install Composer
        - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

        # Install additional tools
        - apt-get update && apt-get install -y git unzip

      update:
        # Install/update Composer dependencies (this installs Drush locally)
        - composer install --no-dev --optimize-autoloader

        # Create symlink to local Drush or use vendor/bin/drush directly
        - ln -sf /var/www/html/vendor/bin/drush /usr/local/bin/drush || echo "Drush symlink failed, will use vendor/bin/drush"

        # Ensure proper file permissions
        - chown -R www-data:www-data /var/www/html

        # Create Drupal settings for Tugboat
        - |
          cat >> web/sites/default/settings.php << 'EOF'
          
          // Tugboat-specific settings for Drupal 10
          if (isset($_SERVER['TUGBOAT_PREVIEW_ID'])) {
            $databases['default']['default'] = [
              'database' => 'tugboat',
              'username' => 'tugboat',
              'password' => 'tugboat',
              'host' => 'mysql',
              'port' => '3306',
              'driver' => 'mysql',
              'prefix' => '',
              'collation' => 'utf8mb4_general_ci',
            ];
            
            $settings['trusted_host_patterns'] = [
              '^.+\.tugboat\.qa$',
              '^.+\.tugboatqa\.com$',
            ];
            
            $settings['config_sync_directory'] = '../config/sync';
            $settings['hash_salt'] = 'tugboat-preview-' . $_SERVER['TUGBOAT_PREVIEW_ID'];
            $settings['file_private_path'] = '/tmp/private';
            $settings['file_temp_path'] = '/tmp';
            $config['system.performance']['css']['preprocess'] = FALSE;
            $config['system.performance']['js']['preprocess'] = FALSE;
            $settings['skip_permissions_hardening'] = TRUE;
            $settings['update_free_access'] = FALSE;
          }
          EOF

        # Create private files directory
        - mkdir -p /tmp/private && chown www-data:www-data /tmp/private

      build:
        # Use vendor/bin/drush explicitly or the symlink
        - ./vendor/bin/drush site:install standard --yes --account-name=admin --account-pass=admin --site-name="Tugboat Preview"

        # Import configuration if it exists
        - ./vendor/bin/drush config:import --yes || echo "No config to import, continuing..."

        # Enable common Drupal 10 modules (adjust as needed)
        - ./vendor/bin/drush pm:enable admin_toolbar admin_toolbar_tools || true

        # Clear all caches
        - ./vendor/bin/drush cache:rebuild

        # Set proper permissions
        - chown -R www-data:www-data web/sites/default/files

  mysql:
    image: tugboatqa/mysql:8.0
    commands:
      update:
        - mysql -e "CREATE DATABASE IF NOT EXISTS tugboat CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;"
